import React, { useState, useRef, useEffect } from 'react';
import { v4 as uuidv4 } from 'uuid';
import { 
  GripVertical, 
  Plus, 
  Trash2, 
  ChevronRight, 
  ChevronDown, 
  CheckSquare, 
  Square,
  Quote,
  Code,
  Divide,
  Info,
  Type,
  EyeOff,
  Sparkles,
  Loader2,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Highlighter,
  AlignLeft,
  AlignCenter,
  AlignRight,
  List,
  ListOrdered,
  Heading1,
  Heading2,
  Heading3
} from 'lucide-react';
import { Block, BlockType } from '../../types';
import SlashMenu from './SlashMenu';

interface BlockEditorProps {
  blocks: Block[];
  onChange: (blocks: Block[]) => void;
  onFocus?: (blockId: string) => void;
}

const BlockEditor: React.FC<BlockEditorProps> = ({ blocks, onChange, onFocus }) => {
  const [focusedBlockId, setFocusedBlockId] = useState<string | null>(null);
  const [slashMenuPosition, setSlashMenuPosition] = useState<{ x: number; y: number } | null>(null);
  const editorRefs = useRef<Record<string, HTMLDivElement | null>>({});

  const updateBlock = (id: string, updates: Partial<Block>) => {
    const newBlocks = blocks.map(b => b.id === id ? { ...b, ...updates } : b);
    onChange(newBlocks);
  };

  const addBlock = (afterId: string, type: BlockType = 'paragraph', content: string = '') => {
    const newBlock: Block = { id: uuidv4(), type, content };
    const index = blocks.findIndex(b => b.id === afterId);
    const newBlocks = [...blocks];
    newBlocks.splice(index + 1, 0, newBlock);
    onChange(newBlocks);
    setTimeout(() => {
      editorRefs.current[newBlock.id]?.focus();
    }, 0);
  };

  const deleteBlock = (id: string) => {
    if (blocks.length <= 1) {
      updateBlock(id, { type: 'paragraph', content: '' });
      return;
    }
    const index = blocks.findIndex(b => b.id === id);
    const newBlocks = blocks.filter(b => b.id !== id);
    onChange(newBlocks);
    if (index > 0) {
      setTimeout(() => {
        const prevBlockId = blocks[index - 1].id;
        editorRefs.current[prevBlockId]?.focus();
        // Place cursor at end
        const range = document.createRange();
        const selection = window.getSelection();
        range.selectNodeContents(editorRefs.current[prevBlockId]!);
        range.collapse(false);
        selection?.removeAllRanges();
        selection?.addRange(range);
      }, 0);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent, block: Block) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      addBlock(block.id);
    } else if (e.key === 'Backspace' && block.content === '' && blocks.length > 1) {
      e.preventDefault();
      deleteBlock(block.id);
    } else if (e.key === '/') {
      const selection = window.getSelection();
      if (selection && selection.rangeCount > 0) {
        const range = selection.getRangeAt(0);
        const rect = range.getBoundingClientRect();
        setSlashMenuPosition({ x: rect.left, y: rect.bottom + window.scrollY });
      }
    } else if (e.key === 'Escape') {
      setSlashMenuPosition(null);
    }
  };

  const handleAiAction = async (type: string, blockId: string, currentContent: string) => {
    updateBlock(blockId, { content: currentContent + ' (✨ AI is thinking...)' });
    
    // Simulate AI processing - in a real app this would call your AI service
    setTimeout(() => {
      let result = currentContent;
      if (type === 'ai-simplify') {
        result = `Simplified: ${currentContent}`;
      } else if (type === 'ai-flashcard') {
        updateBlock(blockId, { type: 'active-recall', content: `Q: What is ${currentContent}?\n\nA: It is an important concept.` });
        return;
      } else if (type === 'ai-expand') {
        result = `${currentContent} - This is a much deeper explanation generated by AI that adds valuable context and examples.`;
      }
      updateBlock(blockId, { content: result });
    }, 1500);
  };

  const handleSlashSelect = (type: BlockType | string) => {
    if (focusedBlockId) {
      const block = blocks.find(b => b.id === focusedBlockId);
      if (block) {
        const newContent = block.content.replace(/\/$/, '');
        
        if (type.startsWith('ai-')) {
          handleAiAction(type, focusedBlockId, newContent);
        } else {
          updateBlock(focusedBlockId, { type: type as BlockType, content: newContent });
        }
      }
    }
    setSlashMenuPosition(null);
  };

  return (
    <div className="relative space-y-1 mt-4">
      <FormattingToolbar 
        activeBlockId={focusedBlockId} 
        onUpdateType={(type) => focusedBlockId && updateBlock(focusedBlockId, { type })}
      />
      
      {blocks.map((block, index) => (
        <div 
          key={block.id} 
          className="group relative flex items-start gap-2"
          onMouseEnter={() => setFocusedBlockId(block.id)}
        >
          <div className="mt-1.5 flex flex-shrink-0 items-center gap-1 opacity-0 transition-opacity group-hover:opacity-100">
            <button className="cursor-grab text-slate-300 hover:text-slate-500">
              <GripVertical size={16} />
            </button>
            <button 
              onClick={() => addBlock(block.id)}
              className="text-slate-300 hover:text-slate-500"
            >
              <Plus size={16} />
            </button>
          </div>

          <div className="flex-1">
            <BlockRenderer 
              block={block} 
              onFocus={() => {
                setFocusedBlockId(block.id);
                onFocus?.(block.id);
              }}
              onBlur={() => {
                if (!slashMenuPosition) setFocusedBlockId(null);
              }}
              onChange={(content) => updateBlock(block.id, { content })}
              onKeyDown={(e) => handleKeyDown(e, block)}
              innerRef={(el) => editorRefs.current[block.id] = el}
            />
          </div>
        </div>
      ))}

      {slashMenuPosition && (
        <SlashMenu 
          position={slashMenuPosition} 
          onSelect={handleSlashSelect} 
          onClose={() => setSlashMenuPosition(null)} 
        />
      )}
    </div>
  );
};

const FormattingToolbar = ({ activeBlockId, onUpdateType }: { activeBlockId: string | null, onUpdateType: (type: BlockType) => void }) => {
  const applyFormat = (command: string, value?: string) => {
    document.execCommand(command, false, value);
  };

  return (
    <div className="sticky top-0 z-20 -mx-4 mb-8 flex flex-wrap items-center gap-1 rounded-2xl border border-slate-200 bg-white/80 p-2 shadow-sm backdrop-blur-md dark:border-slate-800 dark:bg-slate-900/80 sm:mx-0 transition-all">
      <ToolbarButton onClick={() => applyFormat('bold')} icon={Bold} label="Bold" />
      <ToolbarButton onClick={() => applyFormat('italic')} icon={Italic} label="Italic" />
      <ToolbarButton onClick={() => applyFormat('underline')} icon={Underline} label="Underline" />
      <ToolbarButton onClick={() => applyFormat('strikeThrough')} icon={Strikethrough} label="Strikethrough" />
      <div className="mx-1 h-5 w-px bg-slate-200 dark:bg-slate-700" />
      <ToolbarButton onClick={() => applyFormat('justifyLeft')} icon={AlignLeft} label="Align Left" />
      <ToolbarButton onClick={() => applyFormat('justifyCenter')} icon={AlignCenter} label="Align Center" />
      <ToolbarButton onClick={() => applyFormat('justifyRight')} icon={AlignRight} label="Align Right" />
      <div className="mx-1 h-5 w-px bg-slate-200 dark:bg-slate-700" />
      <ToolbarButton onClick={() => applyFormat('hiliteColor', '#fef08a')} icon={Highlighter} label="Highlight" />
      <div className="mx-1 h-5 w-px bg-slate-200 dark:bg-slate-700" />
      <ToolbarButton onClick={() => onUpdateType('h1')} icon={Heading1} label="Heading 1" />
      <ToolbarButton onClick={() => onUpdateType('h2')} icon={Heading2} label="Heading 2" />
      <ToolbarButton onClick={() => onUpdateType('h3')} icon={Heading3} label="Heading 3" />
      <ToolbarButton onClick={() => onUpdateType('bullet')} icon={List} label="Bullet List" />
      <ToolbarButton onClick={() => onUpdateType('numbered')} icon={ListOrdered} label="Numbered List" />
      <ToolbarButton onClick={() => onUpdateType('todo')} icon={CheckSquare} label="Todo List" />
      <ToolbarButton onClick={() => onUpdateType('quote')} icon={Quote} label="Quote" />
      <ToolbarButton onClick={() => onUpdateType('code')} icon={Code} label="Code Block" />
      <ToolbarButton onClick={() => onUpdateType('callout')} icon={Info} label="Callout" />
    </div>
  );
};

const ToolbarButton = ({ onClick, icon: Icon, label }: any) => (
  <button
    onMouseDown={(e) => { e.preventDefault(); onClick(); }}
    className="flex h-8 w-8 items-center justify-center rounded-lg text-slate-500 hover:bg-slate-100 hover:text-slate-900 transition dark:text-slate-400 dark:hover:bg-slate-800 dark:hover:text-slate-100"
    title={label}
  >
    <Icon size={16} />
  </button>
);

interface BlockRendererProps {
  block: Block;
  onChange: (content: string) => void;
  onFocus: () => void;
  onBlur: () => void;
  onKeyDown: (e: React.KeyboardEvent) => void;
  innerRef: (el: HTMLDivElement | null) => void;
}

const BlockRenderer: React.FC<BlockRendererProps> = ({ 
  block, onChange, onFocus, onBlur, onKeyDown, innerRef 
}) => {
  const baseClasses = "w-full outline-none transition-colors min-h-[1.5em] break-words";
  
  const [isRevealed, setIsRevealed] = useState(false);
  const localRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    // Only update innerHTML if it's different to prevent cursor jumps
    // This allows AI generated content or external changes to reflect
    if (localRef.current && localRef.current.innerHTML !== block.content) {
      localRef.current.innerHTML = block.content;
    }
  }, [block.content]);

  const renderContent = () => {
    if (block.type === 'active-recall' && !isRevealed) {
      return (
        <div 
          onClick={() => setIsRevealed(true)}
          className="w-full cursor-pointer rounded-xl bg-slate-900 px-4 py-3 text-transparent hover:bg-slate-800 transition relative overflow-hidden select-none flex items-center justify-center gap-2 font-medium"
        >
          <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-10"></div>
          <EyeOff size={16} className="text-slate-400" />
          <span className="text-slate-400">Click to reveal</span>
        </div>
      );
    }

    return (
      <div
        ref={(el) => {
          localRef.current = el;
          innerRef(el);
        }}
        contentEditable
        suppressContentEditableWarning
        onFocus={onFocus}
        onBlur={onBlur}
        onKeyDown={onKeyDown}
        onInput={(e) => onChange(e.currentTarget.innerHTML)}
        className={`${baseClasses} ${getBlockStyles(block.type)} ${block.type === 'active-recall' ? 'rounded-xl border-2 border-dashed border-sky-200 bg-sky-50/50 p-4 dark:border-sky-900 dark:bg-sky-950/20' : ''}`}
      />
    );
  };

  switch (block.type) {
    case 'h1': return <h1 className="mt-6 mb-2 text-3xl font-bold text-slate-900 dark:text-white">{renderContent()}</h1>;
    case 'h2': return <h2 className="mt-5 mb-2 text-2xl font-semibold text-slate-900 dark:text-white">{renderContent()}</h2>;
    case 'h3': return <h3 className="mt-4 mb-2 text-xl font-semibold text-slate-900 dark:text-white">{renderContent()}</h3>;
    case 'bullet': return (
      <div className="flex items-start gap-2 py-1">
        <span className="mt-2 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-slate-400" />
        {renderContent()}
      </div>
    );
    case 'numbered': return (
      <div className="flex items-start gap-2 py-1">
        <span className="mt-0.5 text-slate-400 font-medium min-w-[1.25rem]">1.</span>
        {renderContent()}
      </div>
    );
    case 'todo': return (
      <div className="flex items-start gap-2 py-1">
        <button className="mt-1 text-slate-400 hover:text-sky-500">
          <Square size={18} />
        </button>
        {renderContent()}
      </div>
    );
    case 'quote': return (
      <div className="my-4 border-l-4 border-slate-200 pl-4 italic text-slate-600 dark:border-slate-700 dark:text-slate-400">
        {renderContent()}
      </div>
    );
    case 'callout': return (
      <div className="my-4 flex items-start gap-3 rounded-2xl border border-sky-100 bg-sky-50/50 p-4 dark:border-sky-900/30 dark:bg-sky-950/20">
        <div className="mt-0.5 text-sky-500"><Info size={20} /></div>
        <div className="flex-1">{renderContent()}</div>
      </div>
    );
    case 'code': return (
      <div className="my-4 rounded-xl bg-slate-900 p-4 font-mono text-sm text-slate-200">
        {renderContent()}
      </div>
    );
    case 'divider': return <div className="my-6 border-t border-slate-100 dark:border-slate-800" />;
    default: return <div className="py-1 text-slate-700 dark:text-slate-300">{renderContent()}</div>;
  }
};

const getBlockStyles = (type: BlockType): string => {
  switch (type) {
    case 'h1': return 'text-3xl font-bold';
    case 'h2': return 'text-2xl font-semibold';
    case 'h3': return 'text-xl font-semibold';
    case 'code': return 'font-mono';
    case 'quote': return 'italic';
    default: return 'text-base leading-relaxed';
  }
};

export default BlockEditor;
